project_id = "yenbgkbykomqxncynbrh"

[functions.generate-text]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.scheduler-publish]
verify_jwt = true

[functions.scheduler-worker]
verify_jwt = false

[functions.channels]
verify_jwt = true

[functions.automation-engine]
verify_jwt = true

[functions.stripe-checkout]
verify_jwt = true

[functions.stripe-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
